name: deploy

on:
  workflow_dispatch:

jobs:
  download-and-deploy-docker: 
      runs-on: ubuntu-latest
      steps:
          - 
            name: Download the latest and docker-compose up
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.KEY }}
              passphrase: ${{ secrets.KEY_PASS }}
              script: |
                docker login ghcr.io --username webbanditten --password ${{ secrets.GH_TOKEN }}
                cd docker/photorenderer
                docker pull ghcr.io/webbanditten/photorenderer:latest
                docker-compose up -d
